"""Auto-generate forward test checklist for FWD_READY experiments.

Creates a markdown checklist the trader prints and follows during the first 30 days live.
Saved to data/checklists/ and path stored in experiments.checklist_path.
"""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

from config.settings import get_settings
from db.queries import Experiment

log = logging.getLogger(__name__)


def generate_checklist(exp: Experiment) -> Path:
    """Generate forward test checklist for a FWD_READY experiment.

    Returns:
        Path to the saved .md checklist file
    """
    cfg = get_settings()
    params = exp.params or {}

    oos_pf_display = exp.oos_pf if exp.oos_pf is not None else "N/A"
    daily_pnl = exp.daily_pnl if exp.daily_pnl is not None else 0
    max_dd_stop = abs(exp.oos_max_dd if exp.oos_max_dd is not None else 500) * 1.5

    content = f"""# Forward Test Checklist
Strategy: {exp.strategy} | Ticker: {exp.ticker} | Timeframe: {exp.timeframe}
Generated: {date.today()} | Experiment ID: {exp.id}
OOS PF: {oos_pf_display} | OOS Daily PnL: ${daily_pnl:.2f}

---

## Pre-Live Checklist

### TradingView Setup
- [ ] Load Pine Script from data/pine_scripts/
- [ ] Apply to {exp.ticker} {exp.timeframe} chart
- [ ] Backtest in TradingView from 2024-01-01 to present
- [ ] Confirm OOS PF is within 5% of {oos_pf_display}
- [ ] Verify commission is set to $1.70/side (cash_per_contract)

### Broker Setup
- [ ] Fund account with minimum $10,000 (for margin on 1 contract)
- [ ] Enable micro futures trading ({exp.ticker})
- [ ] Set default quantity to 1 contract
- [ ] Confirm commission: ~$1.70/side (total ~$3.40 RT)
- [ ] Set price alerts for strategy levels

### Risk Controls
- [ ] Max daily loss: $300 (3x average losing day)
- [ ] Max weekly loss: $700
- [ ] Kill switch: if 5 consecutive losses, pause and review
- [ ] Max drawdown before stopping: ${max_dd_stop:.0f} (based on OOS max DD)

---

## Daily Forward Test Log (30 days)

| Date | Trades | P&L | Notes |
|---|---|---|---|
| | | | |
| | | | |
| | | | |

---

## 30-Day Review Criteria

Pass criteria for continuing live:
- [ ] Total return > $0 (profitable)
- [ ] PF > 1.3 (at least marginal edge)
- [ ] Max consecutive losses < 8
- [ ] No deviation from signal rules

---

## Strategy Parameters (DO NOT change these live)

```
{chr(10).join(f"{k} = {v}" for k, v in params.items())}
```

---

*Generated by quant-v2 automation.*
"""

    checklist_dir = cfg.checklist_dir
    checklist_dir.mkdir(parents=True, exist_ok=True)
    fname = f"{exp.strategy}_{exp.ticker}_{exp.timeframe}_exp{exp.id}_checklist.md"
    path = checklist_dir / fname

    path.write_text(content)
    log.info("Checklist saved: %s", path)
    return path
